version: '3.4'

services:
  cleanarchitecturedb:
    image: postgres:15
  cleanarchitectureapi: 
    image: ${DOCKER_REGISTRY-}cleanarchitectureapi
    build:
      context: .
      dockerfile: src/CleanArchitecturePart1/CleanArchitecturePart1.Api/Dockerfile
  serilogseq:
    image: datalust/seq:2023.4
